//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroBioseguridad.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CrudBioseguridad1Soap")]
    public interface CrudBioseguridad1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVisitante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RegistroBioseguridad.ServiceReference1.Visitante ConsultarVisitante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVisitante", ReplyAction="*")]
        System.Threading.Tasks.Task<RegistroBioseguridad.ServiceReference1.Visitante> ConsultarVisitanteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarRegistrosActuales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MostrarRegistrosActuales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarRegistrosActuales", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MostrarRegistrosActualesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarVisitante_Filtro_Identificacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MostrarVisitante_Filtro_Identificacion(int identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarVisitante_Filtro_Identificacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MostrarVisitante_Filtro_IdentificacionAsync(int identificacion);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Visitante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identificacionField;
        
        private int codigoIngresoField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string organizacionField;
        
        private string fechaIngresoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
                this.RaisePropertyChanged("Identificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CodigoIngreso {
            get {
                return this.codigoIngresoField;
            }
            set {
                this.codigoIngresoField = value;
                this.RaisePropertyChanged("CodigoIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Organizacion {
            get {
                return this.organizacionField;
            }
            set {
                this.organizacionField = value;
                this.RaisePropertyChanged("Organizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("FechaIngreso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CrudBioseguridad1SoapChannel : RegistroBioseguridad.ServiceReference1.CrudBioseguridad1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrudBioseguridad1SoapClient : System.ServiceModel.ClientBase<RegistroBioseguridad.ServiceReference1.CrudBioseguridad1Soap>, RegistroBioseguridad.ServiceReference1.CrudBioseguridad1Soap {
        
        public CrudBioseguridad1SoapClient() {
        }
        
        public CrudBioseguridad1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrudBioseguridad1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudBioseguridad1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudBioseguridad1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public RegistroBioseguridad.ServiceReference1.Visitante ConsultarVisitante() {
            return base.Channel.ConsultarVisitante();
        }
        
        public System.Threading.Tasks.Task<RegistroBioseguridad.ServiceReference1.Visitante> ConsultarVisitanteAsync() {
            return base.Channel.ConsultarVisitanteAsync();
        }
        
        public System.Data.DataSet MostrarRegistrosActuales() {
            return base.Channel.MostrarRegistrosActuales();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MostrarRegistrosActualesAsync() {
            return base.Channel.MostrarRegistrosActualesAsync();
        }
        
        public System.Data.DataSet MostrarVisitante_Filtro_Identificacion(int identificacion) {
            return base.Channel.MostrarVisitante_Filtro_Identificacion(identificacion);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MostrarVisitante_Filtro_IdentificacionAsync(int identificacion) {
            return base.Channel.MostrarVisitante_Filtro_IdentificacionAsync(identificacion);
        }
    }
}
